/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybill_taylor_and_lester;

import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Arrays;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Activity_Fee;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.CAPS;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Classes;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.School_Name;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Student_FinAid;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Student_ID;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Student_Name;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Student_Refund;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Student_Subtotal;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Student_Total;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Technology_Fee;
import static mybill_taylor_and_lester.MyBill_Taylor_and_Lester.Term;

/**
 *
 * @author brownt7272
 */
public class MyBill_JF_FileSave
        extends javax.swing.JFrame
{

    /**
     * Creates new form MyBill_JF_FileSave
     */
    public MyBill_JF_FileSave()
    {
        initComponents();
    }
    
    private static String repeatChar(char c, int length) {
        char[] data = new char[length];
        Arrays.fill(data, c);
        return new String(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SD_Location = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyBill | Taylor & Lester");

        SD_Location.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        SD_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SD_LocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SD_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SD_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SD_LocationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SD_LocationActionPerformed
    {//GEN-HEADEREND:event_SD_LocationActionPerformed
        // Displays the doubles to the houndreth decimal place for USD
        DecimalFormat df = new DecimalFormat("0.00");
        
        // Table Header
        String courseColumns = String.format(("%-48s| %-18s| %-16s| %-18s| %-11s| %-19s| %-11s ")
                                            ,"Course Title"
                                            ,"Course Dates"
                                            ,"Meeting Days"
                                            ,"Course Times"
                                            ,"Location"
                                            ,"Instructor"
                                            ,"Credits");
        
        // Table Rows
        String data = "";
        for (Class section : Classes){
            data += String.format(("%-48s| %-18s| %-16s| %-18s| %-11s| %-19s| %-11s  \n")
                                        ,section.className
                                        ,section.dateRange
                                        ,section.meetingDays
                                        ,section.meetingTimes
                                        ,section.meetingLocation
                                        ,section.instructor
                                        ,section.creditHours);
        }

        // Creates a new file and then opens the file to write the students price breakdown
        try (FileWriter myWriter = new FileWriter(SD_Location.getSelectedFile()+".txt")) {
            
            myWriter.write("Student Name: " + Student_Name
                         + "\nStudent ID: " + Student_ID
                         + "\nSchool Name: " + School_Name
                         + "\nSemester Term: " + Term + "\n\n"
                         + repeatChar('*', 152) + "\n\n"
                         + courseColumns + "\n"
                         + repeatChar('-', 152) + "\n"
                         + data + "\n\n"
                         + repeatChar('-', 34)
                         + "\nYour Subtotal:           $" + df.format(Student_Subtotal) 
                         + "\nActivity Fee:            $" + df.format(Activity_Fee) 
                         + "\nTechnology Fee:          $" + df.format(Technology_Fee)
                         + "\nCAPS Fee:                $" + df.format(CAPS)
                         + "\n" + repeatChar('-', 34)
                         + "\nTotal:                   $" + df.format(Student_Total)
                         + "\nFinancial Aid:           $" + df.format(Student_FinAid)
                         + "\n" + repeatChar('-', 34)
                         + "\nNew Total:               $" + df.format(Student_Refund));
            
            myWriter.close();
        } 
        catch (IOException e) {
            System.out.println("An error occurred.\n");
            System.out.println(e);
        }
        
        this.dispose();
    }//GEN-LAST:event_SD_LocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MyBill_JF_FileSave.class.
                    getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MyBill_JF_FileSave.class.
                    getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MyBill_JF_FileSave.class.
                    getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MyBill_JF_FileSave.class.
                    getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MyBill_JF_FileSave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser SD_Location;
    // End of variables declaration//GEN-END:variables
}
